### PR TITLE
Implemented an option of attaching a source tracking header to HTTP requests

### PR DESCRIPTION
**Pull request by petrsvihlik**
### Motivation

Fixes https://github.com/alanta/Kontent.Statiq/issues/12

Implemented via a new `DeliverySourceTrackingHeaderAttribute` which exposes two constructors:
- Default constructor ensuring the source information will be extracted from the calling assembly.
- Constructor allowing to customize the source tracking header.

Follows the conventions defined in https://github.com/Kentico/Home/wiki/Guidelines-for-Kontent-related-tools#analytics

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Attach this to AssemblyInfo.cs
```c#
[assembly: DeliverySourceTrackingHeader()]
```

Or this to your csproj:

```xml
  <ItemGroup>
    <AssemblyAttribute Include="Kentico.Kontent.Delivery.DeliverySourceTrackingHeader" />
  </ItemGroup>
```

### CODE REVIEW

**Comment by alanta** [comment]
Looks nice and easy to use. Will this pick up any pre-release tag included in the assembly informational version?

**Comment by petrsvihlik** [comment]
We are extracting the version from `FileVersionInfo.ProductVersion` which as far as I know maps to `AssemblyInformationalVersion`. It works fine for us for the other tracking header (`X-KC-SDKID`) and contains the pre-release labels if they're defined.

+ I added support for the pre-release tag to the attribute + added an extra constructor.

**Review by Enngage — APPROVED** [review]
LGTM.

**Comment by petrsvihlik** [comment]
docs https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Developing-plugins

**Pull request merged**
