### PR TITLE
Namespace unifications

### LINKED ISSUE #287: Unify namespaces
### Motivation

Unify namespaces:
- some entities have namespace matching their full project structure
- some entities match just project's namespace

### Proposed solution

Unify namespaces throughout the whole solution structure/match the project namespace in all classes

### PR DESCRIPTION
**Pull request by Simply007**
### Motivation

Fixes #287 

### Checklist

- [ ] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [ ] Docs have been updated (if applicable)
- [ ] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by petrsvihlik** [comment]
please don't do this...leaving abstractions in the root namespace was a conscious and intentional decision to make the whole API easily discoverable. also, you'll create a huge breaking change again + you'd need to update the code generator, etc.

https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/14.0.0


I'm already facing a problem because of this because I have dependencies targeting various versions of the library.
image

suggestion: revert this commit

**Comment by Simply007** [comment]
> please don't do this...leaving abstractions in the root namespace was a conscious and intentional decision to make the whole API easily discoverable. also, you'll create a huge breaking change again + you'd need to update the code generator, etc.
> 
> https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/14.0.0
> 
> I'm already facing a problem because of this because I have dependencies targeting various versions of the library. image
> 
> suggestion: revert this commit

Fair point!

I tried to find any official ruleset for namespaces and folders, but unsuccessfully. In unofficial content, opinions vary. 

Could you elaborate more on your use case with multiple versions of the library that is causing the issues? 

According to the generator's topic, the adjustments are planned. For the end project, it should be one automatic fix to set proper namespaces out of generated code.

In [version 16](https://github.com/Kentico/kontent-delivery-sdk-net/milestone/20), there will be a breaking change with the target framework with at least one namespace changes for Image transformation (#284), so this is a good time to clean up the namespace and set the best practices for code.

I will discuss the pros and cons of this change with maintainers on Thursday (2021-11-18).

---

Saving the commit ID for future reference: https://github.com/Kentico/kontent-delivery-sdk-net/pull/300/commits/c5ea2044cb84e423ca331832030089a1cde21542

**Comment by petrsvihlik** [comment]
>Could you elaborate more on your use case with multiple versions of the library that is causing the issues?

Yeah, it's caused by referencing both Kentico.Kontent.Delivery and Kontent.Statiq (which references K.K.Delivery [too](https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/Kontent.Statiq.csproj)) in my project. So any API breaking change between the two K.K.D. referenced is causing the errors.

>so this is a good time to clean up the namespace and set the best practices for code.

Yeah, that's what we said the last time when we decided to unify it this way. :)

Anyways, if you decide to go this path, I'd really suggest [making the generator part of this repo](https://github.com/Kentico/kontent-delivery-sdk-net/issues/249) and releasing it always together with fresh nugets.

**Comment by Simply007** [comment]
> Yeah, that's what we said the last time when we decided to unify it this way. :)

We will stick with the original approach. I will revert the commit https://github.com/Kentico/kontent-delivery-sdk-net/commit/c5ea2044cb84e423ca331832030089a1cde21542 and add information about namespaces into README at least so that we won't do go this way again.

> Anyways, if you decide to go this path, I'd really suggest making the generator part of this repo and releasing it always together with fresh nugets.

Let's leave this decision for https://github.com/Kentico/kontent-delivery-sdk-net/issues/249

**Pull request merged**
